In [35]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as sym
from fractions import Fraction

np.set_printoptions(suppress=True, linewidth=200, precision=5)

**Forår 2020 5a**

In [36]:
# Find grammatricen ved brug af afsnit 9.3

V = np.array([[2., 1., 0], 
              [2.0, -1., 3.], 
              [-2., 1., 3.], 
              [-2., -1., 0.]])

def Grammatricen(V):
    G = np.dot(V.T, V)
    return G

print(Grammatricen(V))

[[16.  0.  0.]
 [ 0.  4.  0.]
 [ 0.  0. 18.]]


**Forår 2020 7a**

In [37]:
# Bestem det karakteristiske polynomie det(A - \lambda I_3) af A.

A = np.array([[2, 0, 2], 
              [0, 3, 0], 
              [1, 0, 3]])

print(A)

[[2 0 2]
 [0 3 0]
 [1 0 3]]


Vi har matricen A:
$$
\begin{bmatrix}
    2 & 0 & 2 \\
    0 & 3 & 0 \\
    1 & 0 & 3
\end{bmatrix}
$$
Vi finder nu matricen $det(A - \lambda I_3)$, som der gøres i afsnit 21.1:
$$
det(A - \lambda I_3) = det\begin{bmatrix}
    2 - \lambda & 0 & 2 \\
    0 & 3 - \lambda & 0 \\
    1 & 0 & 3 - \lambda
\end{bmatrix}
$$
Denne kan vi nu beregne med definition 21.12 fra notesættet:
$$
det\begin{bmatrix}
    2 - \lambda & 0 & 2 \\
    0 & 3 - \lambda & 0 \\
    1 & 0 & 3 - \lambda
\end{bmatrix} = (2 - \lambda) \cdot \begin{bmatrix}
    3 - \lambda & 0 \\
    0 & 3 - \lambda
\end{bmatrix} - 0 \cdot \begin{bmatrix}
    0 & 0 \\
    1 & 3 - \lambda
\end{bmatrix} + 2 \cdot \begin{bmatrix}
    0 & 3 - \lambda \\
    1 & 0
\end{bmatrix}
$$
For lige at forklare, hvordan det kommer til at være, så er det med brug af def 21.12. Det er vigtigt at forstå, at det element i matricen man ganger med, står i en række og søjle. Den række og søjle den er i forkastes i matricen, som den ganges med. Dvs, hvis man tager elementet i række 0, søjle 0, så består matricen man ganger med her af række 1,2 og søjle 1,2. Ovenstående kan omskrives til 

In [38]:
l = sym.symbols('lambda')
expression = (2 - l) * (3 - l)**2 + (2 * (-(3-l)))
f = sym.factor(expression)
f

-(lambda - 4)*(lambda - 3)*(lambda - 1)

Så vores karakteristiske polynomie efter at have faktoriseret den er:
$$
-(\lambda - 4)(\lambda - 3)(\lambda - 1)
$$

delopgave b) $\\$
$$
-(\lambda - 4)(\lambda - 3)(\lambda - 1) = 0
$$
$$
4, 3, 1
$$
Vi ser, at lambda skal være det samme som tallene de bliver minusset med for at det kan give nul.

In [39]:
# delopgave c)

A = np.array([[2, 0, 2], 
              [0, 3, 0], 
              [1, 0, 3]])

c = A + np.random.random()*0.5 - 0.25
c

array([[2.16335, 0.16335, 2.16335],
       [0.16335, 3.16335, 0.16335],
       [1.16335, 0.16335, 3.16335]])

**Sommer 2020 5b,c,d**

In [40]:
# delopgave b)

w = np.array([1, 2, 3])[:, np.newaxis]
v0 = np.array([3, 1, -3])[:, np.newaxis]
v1 = np.array([1, 0, 1])[:, np.newaxis]
v2 = np.array([-1, 6, 1])[:, np.newaxis]

x0 = np.vdot(w, v0) / np.linalg.norm(v0)**2
x1 = np.vdot(w, v1) / np.linalg.norm(v1)**2
x2 = np.vdot(w, v2) / np.linalg.norm(v2)**2

print(x0, x1, x2)

-0.21052631578947364 1.9999999999999996 0.36842105263157904


Ovenfor har vi brugt proposition 8.17, hvor w er vores u, og vi beregner x-værdierne med formel 8.9, som er værdierne vi fik ovenfor.

In [41]:
# Bekræft værdierne

print(np.allclose(w, x0 * v0 + x1 * v1 + x2 * v2, atol=np.finfo(float).eps))

True


In [43]:
# Parsevals identitet til at beregne norm^2 af w

def parsevals(x0, x1, x2, v0, v1, v2):
    wns = x0**2 * np.linalg.norm(v0)**2 + x1**2 * np.linalg.norm(v1)**2 + x2**2 * np.linalg.norm(v2)**2
    return wns

# Hvis de spørger om normen og ikke 2-normen, så tag kvadratroden af wns ovenfor

ws = np.sqrt(parsevals(x0, x1, x2, v0, v1, v2))

print(parsevals(x0, x1, x2, v0, v1, v2))
print(ws)

14.0
3.7416573867739413
