In [26]:
import sympy as sy
import numpy as np
import matplotlib.pyplot as plt

np.set_printoptions(suppress=True, linewidth=200, precision=5)

# Singulærværdidekomponering

Her tages der udgangspunkt i det samlede notesæt 2023. Fokus ligger på alt omkring SVD, dvs singulærværdier, men også konditionstal (Kapitel 10 og 11).

**SVD** $\\$
Ifølge sætning 10.2 har enhver matrix $A \in \textbf{R}^{m \times n}$ en singulærværdidekomponering. Det vil ende med en matrix, hvor diagonalen udgøres af $\sigma$, som har egenskaben $\sigma_{0} \geq \sigma_{1} \geq ... \geq \sigma_{k-1} \geq 0$ og er singulærværdier for $A$. Søjlerne af $U$ er venstresingulærvektorer og søjlerne af $V$ er højresingulærvektorer. Et eksempel på SVD i python med hjælp af numpy vises nedenfor:

In [35]:
# SVD
x = [-0.01, 1.04, 1.31, 1.95, 2.58, 3.28, 3.86]
a = np.vander(x, 3)

u, s, vt = np.linalg.svd(a)

In [32]:
print(u)

[[-0.00438  0.34515  0.87458  0.15451  0.18039  0.02811 -0.24241]
 [-0.06788  0.50211  0.04591 -0.28109 -0.01728  0.35674  0.73116]
 [-0.10038  0.50099 -0.08745 -0.41996 -0.50705 -0.45696 -0.29835]
 [-0.20381  0.43055 -0.2733   0.82072 -0.14029 -0.05742  0.04278]
 [-0.34192  0.26809 -0.27726 -0.18631  0.79904 -0.18977 -0.15859]
 [-0.53759 -0.02077 -0.07342 -0.1095  -0.19176  0.69483 -0.41668]
 [-0.73338 -0.34652  0.26154  0.02162 -0.12305 -0.37554  0.34209]]


In [33]:
# s udgør singulærværdierne \sigma
print(s)

[21.00392  2.19736  0.73786]


In [34]:
print(vt)

[[-0.95255 -0.28927 -0.09471]
 [-0.25574  0.59188  0.76437]
 [ 0.16505 -0.75233  0.63778]]


**SVD I HÅNDEN** $\\$
Nogle opgaver (nok multiple choice) vil spørge om singulærværdier uden brug af python. Her er en guide til at beregne singulærværdier i latex. Guiden laves ved at løse opgave 1 i forår 2020 eksamenssættet:

Man har en matrix:
$$\begin{bmatrix} 1 & 0 & 0 \\ 0 & -2 & 0 \\ 0 & 0 & 3 \end{bmatrix}$$
som man kan finde værdierne ud fra. Man vil først beregne $A^TA$ således
$$A^TA = \begin{bmatrix} 1 & 0 & 0 \\ 0 & -2 & 0 \\ 0 & 0 & 3 \end{bmatrix} * \begin{bmatrix} 1 & 0 & 0 \\ 0 & -2 & 0 \\ 0 & 0 & 3 \end{bmatrix} = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 4 & 0 \\ 0 & 0 & 9 \end{bmatrix}$$
Derefter vil vi finde egenværdierne for $A^TA$, som gøres ved at løse ligningen $|A^TA - \lambda I| = 0$ (Proposition 21.2), der kan beregnes som:
$$|A^TA - \lambda I| = \begin{bmatrix} 1 - \lambda & 0 & 0 \\ 0 & 4 - \lambda & 0 \\ 0 & 0 & 9 - \lambda \end{bmatrix} = (1 - \lambda)(4 - \lambda)(9 - \lambda)$$
Nu sætter vi udtrykket lig med nul: 
$$(1 - \lambda)(4 - \lambda)(9 - \lambda) = 0$$
og ender med:
$$\lambda = 1, \lambda = 4, \lambda = 9$$
Singulærværdierne finder vi nu, ved at tage kvadratroden af egenværdierne for $A^TA$. Vil har altså:
$$\sigma_{1} = \sqrt{\lambda_{1}} = \sqrt{1} = 1$$
$$\sigma_{2} = \sqrt{\lambda_{2}} = \sqrt{4} = 2$$
$$\sigma_{3} = \sqrt{\lambda_{3}} = \sqrt{9} = 3$$
Svaret til opgaven er altså mulighed A.